# Generated by Django 4.1.3 on 2023-06-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.FloatField(max_length=100)),
                ('vat', models.FloatField(max_length=100)),
                ('total_amount', models.FloatField(max_length=100)),
                ('discount', models.FloatField(max_length=100)),
                ('grand_total', models.FloatField(max_length=100)),
                ('paid', models.FloatField(max_length=100)),
                ('due', models.FloatField(max_length=100)),
                ('payment_type', models.CharField(max_length=100)),
                ('payment_status', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField(max_length=100)),
                ('total', models.FloatField(max_length=100)),
                ('status', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
