# Generated by Django 4.1.3 on 2023-06-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_due_remove_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
    ]
