# Generated by Django 4.1.3 on 2023-06-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_rate_remove_orderitem_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
