# Generated by Django 4.1.3 on 2023-06-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='drug',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='expiration_date',
        ),
    ]
