# Generated by Django 4.1.3 on 2023-06-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_drug_batch_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
