# Generated by Django 4.1.3 on 2023-06-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_date2_alter_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
